name: fl_query
description: Asynchronous data caching, refetching & invalidation library for Flutter
version: 0.3.1
homepage: https://fl-query.vercel.app

issue_tracker: https://github.com/KRTirtho/fl-query/issues

repository: https://github.com/KRTirtho/fl-query


environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  connectivity_plus: ^2.3.9
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  state_notifier: ^0.7.2+1
  mutex: ^3.0.1
  queue: ^3.1.0+1
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.2.0
  build_runner: ^2.2.0
