name: fl_query
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/KRTirtho/fl-query

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  path: ^1.8.0
  # gql: ^0.13.0
  # gql_exec: 0.3.0
  # gql_link: 0.4.0
  # gql_http_link: 0.4.0
  # gql_transform_link: ^0.2.0
  # gql_error_link: ^0.2.0
  # gql_dedupe_link: ^2.0.0
  # normalize: ^0.6.0
  hive: ^2.0.0
  http: ^0.13.0
  collection: ^1.15.0
  web_socket_channel: ^2.0.0
  stream_channel: ^2.1.0
  rxdart: ^0.27.1
  uuid: ^3.0.1

dev_dependencies:
  async: ^2.5.0
  mockito: ^5.0.0
  test: ^1.18.2
  coverage: ^1.0.3
  http_parser: ^4.0.0
  lints: ^1.0.1

# The following section is specific to Flutter.
flutter:
