name: fl_query
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/KRTirtho/fl-query

environment:
  sdk: ">=2.15.1 <3.0.0"
  # flutter: ">=1.17.0"

dependencies:
  # flutter:
  #   sdk: flutter
  meta: ^1.3.0
  path: ^1.8.0
  hive: ^2.0.0
  http: ^0.13.0
  collection: ^1.15.0
  uuid: ^3.0.1
  internet_connection_checker: ^0.0.1+3

dev_dependencies:
  async: ^2.5.0
  mockito: ^5.0.0
  test: ^1.18.2
  coverage: ^1.0.3
  http_parser: ^4.0.0
  lints: ^1.0.1

# The following section is specific to Flutter.
# flutter:
