name: fl_query_devtools
description: Devtools support for Fl-Query
version: 0.1.0+1
homepage: https://fl-query.krtirtho.dev
repository: https://github.com/KRTirtho/fl-query/tree/main/packages/fl_query_devtools
issue_tracker: https://github.com/KRTirtho/fl-query/issues

environment:
  sdk: '>=2.17.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fl_query: ^1.1.0
  json_view: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
