name: example
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  fl_query:
    path: ../

dev_dependencies:
  lints: ^1.0.0
